name: Update views

on:
  schedule:
    - cron: '*/5 * * * *'   # mỗi 5 phút
  workflow_dispatch:        # cho phép trigger thủ công

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch script
        run: |
          python scripts/fetch_views.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/views.json || true
          git commit -m "Update views $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes to commit"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
